version: '2'

services:
 l4d2-php-fpm:
   build: ./php 
   links:
     - l4d2-database
   volumes:
     - ./WEBSTATS:/var/www/html

 l4d2-nginx-front:
   image: nginx:alpine
   links:
     - l4d2-php-fpm
   ports:
     - "9012:80"
   volumes:
     - ./nginx/l4d2.conf:/etc/nginx/conf.d/default.conf:ro
     - ./WEBSTATS:/usr/share/nginx/html

 l4d2-database:
   image: mariadb:5
   volumes:
     - ./mariadb:/var/lib/mysql
   environment:
     - MYSQL_DATABASE=l4d2stats
     - MYSQL_USER=l4d2user
     - MYSQL_PASSWORD=password
     - MYSQL_ROOT_PASSWORD=rootpwd

 l4d2-server:   
   #build: ./l4d2
   image: fculpo/l4d2
   #volumes:
   #  - ./l4d2/cfg:/home/steam/l4d2/left4dead2/cfg
   ports:
     - "27015:27015"
     - "27015:27015/udp"
   #links:
   #  - l4d2-database
